name: shop_easy
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  flutter_riverpod: ^2.3.6
  go_router: ^6.5.0
  intl: ^0.18.0
  firebase_core: ^4.2.1
  heroicons: ^0.11.0
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  rxdart: ^0.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
